#!/usr/bin/env python3
"""Three loose ends: multiplicity, an independent re-implementation, and cost.

(A) MULTIPLICITY, WITH THE CORRECTION APPLIED RATHER THAN DISCLAIMED
The limitations section says roughly a hundred cells are reported with no
multiplicity adjustment, and argues one would change nothing because the central
claims are exact arithmetic rather than tests. That argument is correct and it is
still weaker than doing the correction. So: a clustered permutation test per
forecasting arm, with a family-wise correction across arms, on the paired
differences. If nothing moves, the sentence becomes "we corrected and nothing
moved", which is strictly stronger than "we did not correct".

The permutation respects the design. A paired difference per unit is exchangeable
under the null of no effect ONLY up to its sign, so the null distribution is
generated by flipping signs within a unit, and the unit is a SERIES rather than a
test point wherever a series contributes several -- the same clustering the
robustness table uses, for the same reason.

(B) AN INDEPENDENT RE-IMPLEMENTATION OF THE INDEX ARITHMETIC
The standing failure mode here is a parser or a closed form agreeing with itself:
two of the ten gates re-derive through the layer they check, and the fixture audit
is done by the same person who wrote the builder. R and Julia are already driven by
the cross-language probe, so the index arithmetic -- required rank, required span,
the virtual index, the delivering set -- is rebuilt in R and compared
with the Python implementation. A disagreement is a finding; agreement is the independence the
fixture audit cannot supply on its own.

(C) WHY A SMALL COVERAGE ERROR IS NOT A SMALL ERROR
The generalisation section makes this point for value-at-risk: in ABSOLUTE terms a
one-rank miss is O(1/n), but the quantity a risk report states is the exceedance
RATE, and there the same error is a multiplicative factor. Stated once for one
setting it reads as a rhetorical flourish. Computed across the levels a
practitioner actually requests, it is a table: the tighter the level, the larger the
factor, because 1/(n+1) is a fixed slice of an alpha that is shrinking.

    python probes/multiplicity_and_reimpl.py
"""

import math
import os
import re
import shutil
import subprocess
import sys
import tempfile
from fractions import Fraction as F

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import run_real_data as SK  # noqa: E402

OUT = "outputs/probe_output_multiplicity_and_reimpl.txt"
PERMS = 20000
SEED = 20260806


# ---------------------------------------------------------------------------
# (A) clustered sign-flip permutation test
# ---------------------------------------------------------------------------
def clustered_permutation(per_series, reps=PERMS, seed=SEED):
    """Two-sided p for mean(delta) = 0, flipping SIGNS within clusters.

    `per_series` is one mean paired difference per series. Under the null of no
    effect a unit's difference is as likely to be negative as positive, so the null
    distribution is generated by flipping the sign of whole clusters -- never of
    individual points inside a cluster, which would treat dependent origins as
    independent and shrink the p-value.
    """
    x = np.asarray([v for v in per_series if not math.isnan(v)], float)
    if x.size == 0:
        return float("nan"), 0
    obs = abs(float(x.mean()))
    rng = np.random.default_rng(seed)
    signs = rng.choice((-1.0, 1.0), size=(reps, x.size))
    null = np.abs((signs * x).mean(axis=1))
    # +1 in numerator and denominator: the observed assignment is one of the
    # attainable ones, so a p of exactly zero is not attainable and should not be
    # reported
    p = (1.0 + float(np.sum(null >= obs - 1e-15))) / (reps + 1.0)
    return p, x.size


def exact_signflip_p(gains, losses, units):
    """The two-sided sign-flip p in closed form, for a 0/1 paired arm.

    An arm giving each unit ONE test point has a per-unit paired difference of +1,
    -1 or 0, so the arm's printed counts determine the whole vector.
    Under sign flipping only the m = gains + losses nonzero entries move,
    S = sum of m Rademachers, and the observed statistic is |gains - losses|. There
    is nothing left to simulate, and simulating it caps the resolvable p at
    1/(reps+1) -- which is above several of these.
    """
    m, k = gains + losses, abs(gains - losses)
    if m == 0:
        return 1.0
    if k == 0:
        return 1.0
    # P(|S| >= k) with S = 2B - m, B ~ Bin(m, 1/2); symmetric, so twice one tail
    lo = -(-(m + k) // 2)                       # ceil((m+k)/2)
    tail = sum(math.comb(m, b) for b in range(lo, m + 1))
    return min(1.0, 2.0 * tail / 2.0 ** m)


def cell_differences(gains, losses, units):
    """The arm's actual per-series differences: +1 gains, -1 losses, 0 elsewhere."""
    assert gains + losses <= units, (gains, losses, units)
    return np.array([1.0] * gains + [-1.0] * losses
                    + [0.0] * (units - gains - losses))


CELL_RE = re.compile(
    r"status changed in \d+ of (\d+) units: gains=(\d+)\s+losses=(\d+)")
DELTA_RE = re.compile(r"paired delta \(B - A\)\s+([-+][\d.]+)\s+\(s\.e\. ([\d.]+)\)")
NOMINAL_RE = re.compile(r"nominal (\d\.\d+)")


def read_cell(path, nominal, key):
    """Parse one arm's units, gains, losses, delta and s.e. out of its own output.

    The family used to be eight tuples typed into this file from the tables, and
    the permutation then ran on Gaussian draws matched to each tuple's mean and
    standard error. That is a test on reconstructed data, and it is the single most
    attackable choice in either paper. The counts are in the committed outputs; the
    differences follow from them exactly.
    """
    seen, cur = None, None
    with open(os.path.join(os.path.dirname(os.path.dirname(
            os.path.abspath(__file__))), path)) as fh:
        lines = fh.read().splitlines()
    for idx, ln in enumerate(lines):
        n = NOMINAL_RE.search(ln)
        if n:
            cur = n.group(1)
        if cur != nominal or key not in ln:
            continue
        delta = se = counts = None
        for nxt in lines[idx:idx + 12]:
            d = DELTA_RE.search(nxt)
            if d and delta is None:
                delta, se = float(d.group(1)), float(d.group(2))
            c = CELL_RE.search(nxt)
            if c and counts is None:
                counts = tuple(int(x) for x in c.groups())
        assert counts is not None and delta is not None, (path, key, nominal)
        units, gains, losses = counts
        # One observation per unit, or the counts do not determine the difference
        # vector. A rolling-origin arm stops here rather than being permuted wrongly.
        assert abs(delta - (gains - losses) / units) < 5e-5, (
            f"{path} {key}: printed delta {delta} is not (gains-losses)/units "
            f"= {(gains - losses) / units}; this arm is not one point per unit")
        seen = {"units": units, "gains": gains, "losses": losses,
                "delta": delta, "se": se}
        break
    assert seen is not None, f"no {nominal} cell matching {key!r} in {path}"
    return seen


# The eight forecasting arms, named by the file that measured each. Nothing here is
# a measurement -- every number comes back from read_cell.
FAMILY = [
    ("sktime empirical w=20 (m1)", "outputs/probe_output_real_data.txt",
     "0.90", "empirical  nominal 0.90  initial_window=20"),
    ("sktime empirical w=40 (m1)", "outputs/probe_output_real_data.txt",
     "0.90", "empirical  nominal 0.90  initial_window=40"),
    ("statsforecast m=10 (m1)",
     "outputs/probe_output_real_data_statsforecast.txt", "0.90", "n_windows=10"),
    ("statsforecast m=20 (m1)",
     "outputs/probe_output_real_data_statsforecast.txt", "0.90", "n_windows=20"),
    ("statsforecast m=50 (m1)",
     "outputs/probe_output_real_data_statsforecast.txt", "0.90", "n_windows=50"),
    ("darts cal=15 (m1)", "outputs/probe_output_real_data_darts.txt",
     "0.90", "cal_length=15"),
    ("darts cal=35 (m1)", "outputs/probe_output_real_data_darts.txt",
     "0.90", "cal_length=35"),
    ("darts cal=55 (m1)", "outputs/probe_output_real_data_darts.txt",
     "0.90", "cal_length=55"),
]


def holm(pvals):
    """Holm-Bonferroni adjusted p-values, in the input order.

    Holm rather than plain Bonferroni because it is uniformly at least as powerful
    and no less valid, and because reporting the weakest available correction would
    make "nothing moved" a claim about the correction rather than about the data.
    """
    order = sorted(range(len(pvals)), key=lambda i: pvals[i])
    m, out, running = len(pvals), [0.0] * len(pvals), 0.0
    for rank, i in enumerate(order):
        adj = min(1.0, (m - rank) * pvals[i])
        running = max(running, adj)
        out[i] = running
    return out


# ---------------------------------------------------------------------------
# (B) the index arithmetic, re-implemented in R
# ---------------------------------------------------------------------------
R_CODE = r'''
required_rank <- function(n, cov) {
  k <- ceiling((n + 1) * cov)
  if (k <= n) k else NA_integer_
}
required_span <- function(n, cov) {
  k <- ceiling((n + 1) * cov); m <- n + 1 - k; a <- m %/% 2
  c(a, a + k, k)
}
h_linear  <- function(n, q) 1 + q * (n - 1)
h_weibull <- function(n, q) q * (n + 1)
h_invcdf  <- function(n, q) ceiling(q * n)
h_higher  <- function(n, q) ceiling(q * (n - 1)) + 1
delivers  <- function(hf, n, cov) floor(hf(n, cov)) >= ceiling((n + 1) * cov)

out <- c()
for (n in c(2, 3, 7, 9, 10, 19, 20, 29, 47, 50, 99, 100, 200, 501)) {
  for (cov in c(0.90, 0.95, 2/3, 5/7)) {
    rr <- required_rank(n, cov)
    sp <- required_span(n, cov)
    out <- c(out, sprintf("%d %.10f %s %d %d %d %.10f %.10f %d %d %d %d %d %d",
      n, cov, ifelse(is.na(rr), "NA", as.character(rr)),
      sp[1], sp[2], sp[3],
      h_linear(n, cov), h_weibull(n, cov), h_invcdf(n, cov), h_higher(n, cov),
      as.integer(delivers(h_linear, n, cov)),
      as.integer(delivers(h_weibull, n, cov)),
      as.integer(delivers(h_invcdf, n, cov)),
      as.integer(delivers(h_higher, n, cov))))
  }
}
cat(out, sep = "\n")
cat("\n")
'''


def py_reference(n, cov):
    """The Python side of the cross-check, from the shipped probe module."""
    rr = SK.required_rank(n, cov)
    a, b, k = SK.required_span(n, cov)
    c = F(cov).limit_denominator(10 ** 6)

    def dels(h):
        return int(math.floor(h) >= math.ceil(F(n + 1) * c))
    h_lin = 1 + c * (n - 1)
    h_wei = c * (n + 1)
    h_inv = math.ceil(c * n)
    h_hig = math.ceil(c * (n - 1)) + 1
    return {"rr": rr, "a": a, "b": b, "k": k,
            "h_lin": float(h_lin), "h_wei": float(h_wei),
            "h_inv": h_inv, "h_hig": h_hig,
            "d_lin": dels(h_lin), "d_wei": dels(h_wei),
            "d_inv": dels(h_inv), "d_hig": dels(h_hig)}


def run_r():
    if not shutil.which("Rscript"):
        return None, "Rscript not on PATH"
    with tempfile.NamedTemporaryFile("w", suffix=".R", delete=False) as fh:
        fh.write(R_CODE)
        path = fh.name
    try:
        p = subprocess.run(["Rscript", "--vanilla", path],
                           capture_output=True, text=True, timeout=300)
    finally:
        os.unlink(path)
    if p.returncode != 0:
        return None, (p.stderr or "").strip()[:160]
    rows = {}
    for ln in p.stdout.strip().splitlines():
        f = ln.split()
        if len(f) != 14:
            continue
        n, cov = int(f[0]), float(f[1])
        rows[(n, round(cov, 10))] = {
            "rr": None if f[2] == "NA" else int(f[2]),
            "a": int(f[3]), "b": int(f[4]), "k": int(f[5]),
            "h_lin": float(f[6]), "h_wei": float(f[7]),
            "h_inv": int(f[8]), "h_hig": int(f[9]),
            "d_lin": int(f[10]), "d_wei": int(f[11]),
            "d_inv": int(f[12]), "d_hig": int(f[13]),
        }
    return rows, None


# ---------------------------------------------------------------------------
# (C) absolute error against exceedance-rate error
# ---------------------------------------------------------------------------
def exceedance_factor(n, level):
    """What a one-rank miss costs, absolutely and as a rate.

    A helper landing one rank short of k* delivers (k*-1)/(n+1) instead of
    k*/(n+1). One lost rank changes coverage by 1/(n+1). The
    exceedance rate printed in a risk report is 1 - coverage, so the RATIO of the
    delivered rate to the requested one is what a reader of that report sees.
    """
    c = F(level).limit_denominator(10 ** 6)
    k = math.ceil(F(n + 1) * c)
    if k > n or k < 2:
        return None
    got = F(k - 1, n + 1)
    want = F(k, n + 1)
    exc_got, exc_want = 1 - got, 1 - want
    return {"abs": float(want - got), "rate_got": float(exc_got),
            "rate_want": float(exc_want),
            "factor": float(exc_got / exc_want) if exc_want > 0 else float("inf")}


def self_check():
    # (A) the test must reject a planted effect and not reject noise
    rng = np.random.default_rng(3)
    p_null, _ = clustered_permutation(rng.normal(0, 1, 60), reps=4000, seed=1)
    assert p_null > 0.05, p_null
    p_eff, _ = clustered_permutation(rng.normal(1.2, 1, 60), reps=4000, seed=1)
    assert p_eff < 0.01, p_eff
    # a p of exactly zero must be unreachable
    assert clustered_permutation(np.ones(40), reps=999, seed=1)[0] > 0
    # (A) the closed-form sign-flip p must agree with the simulation it replaces,
    # and must be the thing that is right where the simulation runs out of
    # resolution: 2^(1-g) for an all-positive arm.
    for g in (3, 5, 9):
        mc, _ = clustered_permutation(cell_differences(g, 0, 250), reps=40000,
                                      seed=7)
        ex = exact_signflip_p(g, 0, 250)
        assert abs(ex - 2.0 ** (1 - g)) < 1e-12, (g, ex)
        assert abs(mc - ex) < 4 * math.sqrt(ex * (1 - ex) / 40000) + 1e-4, (g, mc, ex)
    # a two-sided p must not depend on the sign, and losses must count against gains
    assert exact_signflip_p(0, 6, 250) == exact_signflip_p(6, 0, 250)
    assert exact_signflip_p(5, 5, 250) == 1.0
    assert exact_signflip_p(9, 2, 250) > exact_signflip_p(9, 0, 250)
    # (A) Holm must be monotone, bounded by 1, and no smaller than the raw p
    raw = [0.001, 0.02, 0.2, 0.9]
    adj = holm(raw)
    assert all(a >= r - 1e-12 for a, r in zip(adj, raw)), (raw, adj)
    assert all(a <= 1 for a in adj)
    assert adj == sorted(adj), adj
    # (C) one lost rank changes coverage by 1/(n+1), and the rate factor
    # grows as the level tightens -- which is the whole point of section (C)
    a90 = exceedance_factor(200, 0.90)
    a99 = exceedance_factor(200, 0.99)
    assert abs(a90["abs"] - a99["abs"]) < 1e-12, (a90, a99)
    assert a99["factor"] > a90["factor"] > 1.0, (a90, a99)


self_check()


def main():
    lines = []

    def say(s=""):
        print(s, flush=True)
        lines.append(s)

    say("=" * 104)
    say("MULTIPLICITY, AN INDEPENDENT RE-IMPLEMENTATION, AND WHAT A SMALL ERROR COSTS")
    say("=" * 104)
    say("self_check() passed at import: the permutation test rejects a planted")
    say("effect and spares noise, a p of exactly zero is unreachable, Holm is")
    say("monotone and never below the raw p, and the absolute one-rank miss is")
    say("1/(n+1) at every level while the rate factor grows as the level tightens.")
    say("")

    # ---------------- (A) --------------------------------------------------
    say("-" * 104)
    say("(A) CLUSTERED PERMUTATION TESTS, WITH A FAMILY-WISE CORRECTION")
    say("-" * 104)
    say("Signs are sign-changed by SERIES cluster, not by test point, so rolling")
    say("origins do not masquerade as separate units. Holm-Bonferroni across the")
    say("arms in the family. The paired arms are one-sided by construction where")
    say("arm B contains arm A, so a two-sided p is conservative here and that is the")
    say("direction to err in.")
    say("")
    say("THE DIFFERENCES ARE THE ARMS' OWN, NOT A RECONSTRUCTION. An earlier version")
    say("of this section sign-flipped synthetic draws calibrated to each cell's reported mean")
    say("and standard error, because the per-series differences looked absent from the")
    say("committed outputs. They are not absent. Each arm contributes one")
    say("point per series; its per-series entry falls in {-1, 0, +1}, and the")
    say("printed gains and losses determine that vector. Every cell below is")
    say("parsed out of the file named beside it, and the parse asserts that the")
    say("printed delta equals (gains - losses)/units -- a rolling-origin arm")
    say("fails there instead of being permuted as though it had one point per series.")
    say("")
    say("The p is then exact rather than simulated. Sign flipping moves only the")
    say("nonzero entries, so P(|S| >= |gains - losses|) for S a sum of Rademachers is")
    say("a binomial tail with nothing left to estimate. The simulation is kept beside")
    say("it as a check and not as the answer, because it cannot resolve below")
    say(f"1/{PERMS + 1} = {1.0 / (PERMS + 1):.3e} and the smallest of these is well under that.")
    say("")
    arms, pvals = [], []
    say(f"{'arm':<30} {'source'.ljust(14)} {'delta':>9} {'units':>6} "
        f"{'g':>4} {'l':>3} {'exact p':>11} {'MC p':>9} {'Holm p':>10}")
    say("-" * 104)
    for name, path, nominal, key in FAMILY:
        c = read_cell(path, nominal, key)
        x = cell_differences(c["gains"], c["losses"], c["units"])
        p = exact_signflip_p(c["gains"], c["losses"], c["units"])
        mc, _ = clustered_permutation(x)
        arms.append((name, c, p, mc,
                     os.path.basename(path).replace("probe_output_", "")
                     .replace(".txt", "")))
        pvals.append(p)
    adj = holm(pvals)
    for (name, c, p, mc, src), a in zip(arms, adj):
        say(f"{name:<30} {src[:14]:<14} {c['delta']:>+9.4f} {c['units']:>6} "
            f"{c['gains']:>4} {c['losses']:>3} {p:>11.3e} {mc:>9.5f} {a:>10.5f}")
    say("")
    say("The MC column is the simulation, kept as a check on the closed form and not")
    say("as the result: it agrees wherever it has the resolution to, and floors at")
    say(f"{1.0 / (PERMS + 1):.5f} where it does not.")
    say("")
    arms = [(name, c["delta"], c["se"], c["units"], p)
            for name, c, p, _, _ in arms]
    surv = sum(1 for a in adj if a < 0.05)
    dropped = [(n, d, p, a) for (n, d, _, _, p), a in zip(arms, adj) if a >= 0.05]
    say(f"{surv} of {len(adj)} arms remain significant at 0.05 after "
        f"Holm-Bonferroni across the family.")
    if dropped:
        say("")
        say("The arm(s) that do NOT survive, named rather than dropped quietly:")
        for n, d, p, a in dropped:
            say(f"    {n:<32} delta {d:+.4f}  raw p {p:.5f}  Holm p {a:.5f}")
        say("These are the smallest effects in the family, which is what a")
        say("family-wise correction is for. The disclosure can now say what")
        say("survives correction and what does not, instead of declining to")
        say("correct and asserting that it would not have mattered.")
    else:
        say("So the correction changes nothing, which is the sentence worth having:")
        say("the multiplicity disclosure can say 'we corrected and nothing moved'")
        say("instead of 'we did not correct'.")
    say("")
    say("One limit, stated. The exactly-zero cells are omitted from the family,")
    say("because a difference that is identically zero by construction has no null")
    say("to reject and carrying it would inflate the family to weaken the correction")
    say("applied to the rest. The coincidence cells of the audit's severity section")
    say("are that case, and they are evidence by being zero rather than by a p.")
    say("")

    # ---------------- (B) --------------------------------------------------
    say("-" * 104)
    say("(B) THE INDEX ARITHMETIC, rebuilt in R and compared")
    say("-" * 104)
    rrows, rerr = run_r()
    if rrows is None:
        say(f"NOT ATTEMPTED: {rerr}")
    else:
        fields = ["rr", "a", "b", "k", "h_inv", "h_hig",
                  "d_lin", "d_wei", "d_inv", "d_hig"]
        checked, disagree = 0, []
        for (n, cov), rr in sorted(rrows.items()):
            py = py_reference(n, cov)
            for f in fields:
                checked += 1
                if py[f] != rr[f]:
                    disagree.append((n, cov, f, py[f], rr[f]))
            for f in ("h_lin", "h_wei"):
                checked += 1
                if abs(py[f] - rr[f]) > 1e-9:
                    disagree.append((n, cov, f, py[f], rr[f]))
        say(f"cells: {len(rrows)}   field comparisons: {checked}   "
            f"disagreements: {len(disagree)}")
        for d in disagree[:12]:
            say(f"    n={d[0]} cov={d[1]:.6f} {d[2]}: python={d[3]} R={d[4]}")
        if not disagree:
            say("")
            say("Two implementations written against the same definitions in two")
            say("languages agree on the needed rank, the interval span, both")
            say("virtual indices and all four delivery decisions, at every cell.")
            say("That is the independence the fixture audit cannot supply: checks 2")
            say("and 4 re-derive through the layer they check, and check 5's oracle")
            say("is reviewed by the builder author.")
    say("")

    # ---------------- (C) --------------------------------------------------
    say("-" * 104)
    say("(C) THE SAME ONE-RANK MISS, ABSOLUTELY AND AS AN EXCEEDANCE RATE")
    say("-" * 104)
    say("A helper one rank short delivers (k*-1)/(n+1) rather than k*/(n+1). The")
    say("one-rank coverage change is 1/(n+1) at every level. In a")
    say("risk report or alerting summary, the stated rate is 1 - coverage; the same miss becomes")
    say("a larger rate multiplier at tighter requested levels.")
    say("")
    say(f"{'n':>6} {'level':>7} {'abs miss':>10} {'rate asked':>11} "
        f"{'rate got':>10} {'factor':>8}")
    say("-" * 104)
    worst = None
    for n in (50, 200, 1000):
        for level in (0.90, 0.95, 0.99, 0.999):
            r = exceedance_factor(n, level)
            if r is None:
                say(f"{n:>6} {level:>7.3f}   infeasible at this n")
                continue
            say(f"{n:>6} {level:>7.3f} {r['abs']:>10.5f} {r['rate_want']:>11.5f} "
                f"{r['rate_got']:>10.5f} {r['factor']:>8.2f}x")
            if worst is None or r["factor"] > worst[0]:
                worst = (r["factor"], n, level)
        say("")
    if worst:
        say(f"Worst factor here: {worst[0]:.2f}x at n={worst[1]}, level={worst[2]}.")
    say("The absolute column is flat and the factor column is not. A reader who")
    say("judges the defect by the absolute column is reading the one that does not")
    say("depend on the level they asked for.")

    path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                        OUT)
    with open(path, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"\nwritten -> {path}")


if __name__ == "__main__":
    main()
