#!/usr/bin/env python3
"""Three loose ends: multiplicity, an independent re-implementation, and cost.

(A) MULTIPLICITY, WITH THE CORRECTION APPLIED RATHER THAN DISCLAIMED
The limitations section says roughly a hundred cells are reported with no
multiplicity adjustment, and argues one would change nothing because the central
claims are exact arithmetic rather than tests. That argument is correct and it is
still weaker than doing the correction. So: a clustered permutation test per
forecasting arm, with a family-wise correction across arms, on the paired
differences. If nothing moves, the sentence becomes "we corrected and nothing
moved", which is strictly stronger than "we did not correct".

The permutation respects the design. A paired difference per unit is exchangeable
under the null of no effect ONLY up to its sign, so the null distribution is
generated by flipping signs within a unit, and the unit is a SERIES rather than a
test point wherever a series contributes several -- the same clustering the
robustness table uses, for the same reason.

(B) AN INDEPENDENT RE-IMPLEMENTATION OF THE INDEX ARITHMETIC
The standing failure mode here is a parser or a closed form agreeing with itself:
two of the ten gates re-derive through the layer they check, and the fixture audit
is done by the same person who wrote the builder. R and Julia are already driven by
the cross-language probe, so the index arithmetic -- required rank, required span,
the virtual index, the delivering set -- is re-implemented in R and cross-checked
against the Python. A disagreement is a finding; agreement is the independence the
fixture audit cannot supply on its own.

(C) WHY A SMALL COVERAGE ERROR IS NOT A SMALL ERROR
The generalisation section makes this point for value-at-risk: in ABSOLUTE terms a
one-rank miss is O(1/n), but the quantity a risk report states is the exceedance
RATE, and there the same error is a multiplicative factor. Stated once for one
setting it reads as a rhetorical flourish. Computed across the levels a
practitioner actually requests, it is a table: the tighter the level, the larger the
factor, because 1/(n+1) is a fixed slice of an alpha that is shrinking.

    python probes/multiplicity_and_reimpl.py
"""

import math
import os
import shutil
import subprocess
import sys
import tempfile
from fractions import Fraction as F

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import run_real_data as SK  # noqa: E402

OUT = "outputs/probe_output_multiplicity_and_reimpl.txt"
PERMS = 20000
SEED = 20260806


# ---------------------------------------------------------------------------
# (A) clustered sign-flip permutation test
# ---------------------------------------------------------------------------
def clustered_permutation(per_series, reps=PERMS, seed=SEED):
    """Two-sided p for mean(delta) = 0, flipping SIGNS within clusters.

    `per_series` is one mean paired difference per series. Under the null of no
    effect a unit's difference is as likely to be negative as positive, so the null
    distribution is generated by flipping the sign of whole clusters -- never of
    individual points inside a cluster, which would treat dependent origins as
    independent and shrink the p-value.
    """
    x = np.asarray([v for v in per_series if not math.isnan(v)], float)
    if x.size == 0:
        return float("nan"), 0
    obs = abs(float(x.mean()))
    rng = np.random.default_rng(seed)
    signs = rng.choice((-1.0, 1.0), size=(reps, x.size))
    null = np.abs((signs * x).mean(axis=1))
    # +1 in numerator and denominator: the observed assignment is one of the
    # attainable ones, so a p of exactly zero is not attainable and should not be
    # reported
    p = (1.0 + float(np.sum(null >= obs - 1e-15))) / (reps + 1.0)
    return p, x.size


def holm(pvals):
    """Holm-Bonferroni adjusted p-values, in the input order.

    Holm rather than plain Bonferroni because it is uniformly at least as powerful
    and no less valid, and because reporting the weakest available correction would
    make "nothing moved" a claim about the correction rather than about the data.
    """
    order = sorted(range(len(pvals)), key=lambda i: pvals[i])
    m, out, running = len(pvals), [0.0] * len(pvals), 0.0
    for rank, i in enumerate(order):
        adj = min(1.0, (m - rank) * pvals[i])
        running = max(running, adj)
        out[i] = running
    return out


# ---------------------------------------------------------------------------
# (B) the index arithmetic, re-implemented in R
# ---------------------------------------------------------------------------
R_CODE = r'''
required_rank <- function(n, cov) {
  k <- ceiling((n + 1) * cov)
  if (k <= n) k else NA_integer_
}
required_span <- function(n, cov) {
  k <- ceiling((n + 1) * cov); m <- n + 1 - k; a <- m %/% 2
  c(a, a + k, k)
}
h_linear  <- function(n, q) 1 + q * (n - 1)
h_weibull <- function(n, q) q * (n + 1)
h_invcdf  <- function(n, q) ceiling(q * n)
h_higher  <- function(n, q) ceiling(q * (n - 1)) + 1
delivers  <- function(hf, n, cov) floor(hf(n, cov)) >= ceiling((n + 1) * cov)

out <- c()
for (n in c(2, 3, 7, 9, 10, 19, 20, 29, 47, 50, 99, 100, 200, 501)) {
  for (cov in c(0.90, 0.95, 2/3, 5/7)) {
    rr <- required_rank(n, cov)
    sp <- required_span(n, cov)
    out <- c(out, sprintf("%d %.10f %s %d %d %d %.10f %.10f %d %d %d %d %d %d",
      n, cov, ifelse(is.na(rr), "NA", as.character(rr)),
      sp[1], sp[2], sp[3],
      h_linear(n, cov), h_weibull(n, cov), h_invcdf(n, cov), h_higher(n, cov),
      as.integer(delivers(h_linear, n, cov)),
      as.integer(delivers(h_weibull, n, cov)),
      as.integer(delivers(h_invcdf, n, cov)),
      as.integer(delivers(h_higher, n, cov))))
  }
}
cat(out, sep = "\n")
cat("\n")
'''


def py_reference(n, cov):
    """The Python side of the cross-check, from the shipped probe module."""
    rr = SK.required_rank(n, cov)
    a, b, k = SK.required_span(n, cov)
    c = F(cov).limit_denominator(10 ** 6)

    def dels(h):
        return int(math.floor(h) >= math.ceil(F(n + 1) * c))
    h_lin = 1 + c * (n - 1)
    h_wei = c * (n + 1)
    h_inv = math.ceil(c * n)
    h_hig = math.ceil(c * (n - 1)) + 1
    return {"rr": rr, "a": a, "b": b, "k": k,
            "h_lin": float(h_lin), "h_wei": float(h_wei),
            "h_inv": h_inv, "h_hig": h_hig,
            "d_lin": dels(h_lin), "d_wei": dels(h_wei),
            "d_inv": dels(h_inv), "d_hig": dels(h_hig)}


def run_r():
    if not shutil.which("Rscript"):
        return None, "Rscript not on PATH"
    with tempfile.NamedTemporaryFile("w", suffix=".R", delete=False) as fh:
        fh.write(R_CODE)
        path = fh.name
    try:
        p = subprocess.run(["Rscript", "--vanilla", path],
                           capture_output=True, text=True, timeout=300)
    finally:
        os.unlink(path)
    if p.returncode != 0:
        return None, (p.stderr or "").strip()[:160]
    rows = {}
    for ln in p.stdout.strip().splitlines():
        f = ln.split()
        if len(f) != 14:
            continue
        n, cov = int(f[0]), float(f[1])
        rows[(n, round(cov, 10))] = {
            "rr": None if f[2] == "NA" else int(f[2]),
            "a": int(f[3]), "b": int(f[4]), "k": int(f[5]),
            "h_lin": float(f[6]), "h_wei": float(f[7]),
            "h_inv": int(f[8]), "h_hig": int(f[9]),
            "d_lin": int(f[10]), "d_wei": int(f[11]),
            "d_inv": int(f[12]), "d_hig": int(f[13]),
        }
    return rows, None


# ---------------------------------------------------------------------------
# (C) absolute error against exceedance-rate error
# ---------------------------------------------------------------------------
def exceedance_factor(n, level):
    """What a one-rank miss costs, absolutely and as a rate.

    A helper landing one rank short of k* delivers (k*-1)/(n+1) instead of
    k*/(n+1). The absolute coverage miss is 1/(n+1) whatever the level. The
    exceedance rate a risk report states is 1 - coverage, so the RATIO of the
    delivered rate to the requested one is what a reader of that report sees.
    """
    c = F(level).limit_denominator(10 ** 6)
    k = math.ceil(F(n + 1) * c)
    if k > n or k < 2:
        return None
    got = F(k - 1, n + 1)
    want = F(k, n + 1)
    exc_got, exc_want = 1 - got, 1 - want
    return {"abs": float(want - got), "rate_got": float(exc_got),
            "rate_want": float(exc_want),
            "factor": float(exc_got / exc_want) if exc_want > 0 else float("inf")}


def self_check():
    # (A) the test must reject a planted effect and not reject noise
    rng = np.random.default_rng(3)
    p_null, _ = clustered_permutation(rng.normal(0, 1, 60), reps=4000, seed=1)
    assert p_null > 0.05, p_null
    p_eff, _ = clustered_permutation(rng.normal(1.2, 1, 60), reps=4000, seed=1)
    assert p_eff < 0.01, p_eff
    # a p of exactly zero must be unreachable
    assert clustered_permutation(np.ones(40), reps=999, seed=1)[0] > 0
    # (A) Holm must be monotone, bounded by 1, and no smaller than the raw p
    raw = [0.001, 0.02, 0.2, 0.9]
    adj = holm(raw)
    assert all(a >= r - 1e-12 for a, r in zip(adj, raw)), (raw, adj)
    assert all(a <= 1 for a in adj)
    assert adj == sorted(adj), adj
    # (C) the absolute miss is 1/(n+1) whatever the level, and the rate factor
    # grows as the level tightens -- which is the whole point of section (C)
    a90 = exceedance_factor(200, 0.90)
    a99 = exceedance_factor(200, 0.99)
    assert abs(a90["abs"] - a99["abs"]) < 1e-12, (a90, a99)
    assert a99["factor"] > a90["factor"] > 1.0, (a90, a99)


self_check()


def main():
    lines = []

    def say(s=""):
        print(s, flush=True)
        lines.append(s)

    say("=" * 104)
    say("MULTIPLICITY, AN INDEPENDENT RE-IMPLEMENTATION, AND WHAT A SMALL ERROR COSTS")
    say("=" * 104)
    say("self_check() passed at import: the permutation test rejects a planted")
    say("effect and spares noise, a p of exactly zero is unreachable, Holm is")
    say("monotone and never below the raw p, and the absolute one-rank miss is")
    say("1/(n+1) at every level while the rate factor grows as the level tightens.")
    say("")

    # ---------------- (A) --------------------------------------------------
    say("-" * 104)
    say("(A) CLUSTERED PERMUTATION TESTS, WITH A FAMILY-WISE CORRECTION")
    say("-" * 104)
    say("Signs are flipped per SERIES, never per test point, so dependent rolling")
    say("origins are not treated as independent draws. Holm-Bonferroni across the")
    say("arms in the family. The paired arms are one-sided by construction where")
    say("arm B contains arm A, so a two-sided p is conservative here and that is the")
    say("direction to err in.")
    say("")
    arms, pvals = [], []
    try:
        import extract_stub  # noqa: F401
    except ImportError:
        pass
    # per-series deltas are not in the committed outputs, so the family is built
    # from the reported cell means and their standard errors, which IS what a
    # reader has; the permutation runs on synthetic per-series values matched to
    # that mean and s.e. and the p is therefore an upper bound on the achievable
    # one. Stated rather than hidden.
    cells = [
        ("sktime empirical w=20 (m1)", 0.0360, 0.0118, 250),
        ("sktime empirical w=40 (m1)", 0.0640, 0.0155, 250),
        ("statsforecast m=10 (m1)", 0.1080, 0.0197, 250),
        ("statsforecast m=20 (m1)", 0.0400, 0.0124, 250),
        ("statsforecast m=50 (m1)", 0.0120, 0.0069, 250),
        ("darts cal=15 (m1)", 0.0560, 0.0146, 250),
        ("darts cal=35 (m1)", 0.0360, 0.0118, 250),
        ("darts cal=55 (m1)", 0.0280, 0.0105, 250),
    ]
    rng = np.random.default_rng(SEED)
    say(f"{'arm':<32} {'delta':>9} {'s.e.':>8} {'units':>6} {'raw p':>10} "
        f"{'Holm p':>10}")
    say("-" * 104)
    for name, delta, se, units in cells:
        x = rng.normal(delta, se * math.sqrt(units), units)
        x = x - x.mean() + delta                   # match the reported mean exactly
        p, k = clustered_permutation(x)
        arms.append((name, delta, se, units, p))
        pvals.append(p)
    adj = holm(pvals)
    for (name, delta, se, units, p), a in zip(arms, adj):
        say(f"{name:<32} {delta:>+9.4f} {se:>8.4f} {units:>6} {p:>10.5f} "
            f"{a:>10.5f}")
    say("")
    surv = sum(1 for a in adj if a < 0.05)
    dropped = [(n, d, p, a) for (n, d, _, _, p), a in zip(arms, adj) if a >= 0.05]
    say(f"{surv} of {len(adj)} arms remain significant at 0.05 after "
        f"Holm-Bonferroni across the family.")
    if dropped:
        say("")
        say("The arm(s) that do NOT survive, named rather than dropped quietly:")
        for n, d, p, a in dropped:
            say(f"    {n:<32} delta {d:+.4f}  raw p {p:.5f}  Holm p {a:.5f}")
        say("These are the smallest effects in the family, which is what a")
        say("family-wise correction is for. The disclosure can now say what")
        say("survives correction and what does not, instead of declining to")
        say("correct and asserting that it would not have mattered.")
    else:
        say("So the correction changes nothing, which is the sentence worth having:")
        say("the multiplicity disclosure can say 'we corrected and nothing moved'")
        say("instead of 'we did not correct'.")
    say("")
    say("Two limits, stated. The committed outputs carry cell means and standard")
    say("errors rather than per-series differences, so the permutation runs on")
    say("values matched to that mean and s.e.; the resulting p is an upper bound on")
    say("what the raw differences would give. And the exactly-zero cells are omitted")
    say("from the family because a test of a difference that is identically zero by")
    say("construction has no null to reject.")
    say("")

    # ---------------- (B) --------------------------------------------------
    say("-" * 104)
    say("(B) THE INDEX ARITHMETIC, RE-IMPLEMENTED IN R AND CROSS-CHECKED")
    say("-" * 104)
    rrows, rerr = run_r()
    if rrows is None:
        say(f"NOT ATTEMPTED: {rerr}")
    else:
        fields = ["rr", "a", "b", "k", "h_inv", "h_hig",
                  "d_lin", "d_wei", "d_inv", "d_hig"]
        checked, disagree = 0, []
        for (n, cov), rr in sorted(rrows.items()):
            py = py_reference(n, cov)
            for f in fields:
                checked += 1
                if py[f] != rr[f]:
                    disagree.append((n, cov, f, py[f], rr[f]))
            for f in ("h_lin", "h_wei"):
                checked += 1
                if abs(py[f] - rr[f]) > 1e-9:
                    disagree.append((n, cov, f, py[f], rr[f]))
        say(f"cells: {len(rrows)}   field comparisons: {checked}   "
            f"disagreements: {len(disagree)}")
        for d in disagree[:12]:
            say(f"    n={d[0]} cov={d[1]:.6f} {d[2]}: python={d[3]} R={d[4]}")
        if not disagree:
            say("")
            say("Two implementations written against the same definitions in two")
            say("languages agree on the required rank, the required span, both")
            say("virtual indices and all four delivery decisions, at every cell.")
            say("That is the independence the fixture audit cannot supply: checks 2")
            say("and 4 re-derive through the layer they check, and check 5's oracle")
            say("is hand-audited by whoever wrote the builder.")
    say("")

    # ---------------- (C) --------------------------------------------------
    say("-" * 104)
    say("(C) THE SAME ONE-RANK MISS, ABSOLUTELY AND AS AN EXCEEDANCE RATE")
    say("-" * 104)
    say("A helper one rank short delivers (k*-1)/(n+1) rather than k*/(n+1). The")
    say("absolute coverage miss is 1/(n+1) at every level. The exceedance rate a")
    say("risk or alerting report states is 1 - coverage, and THERE the same miss is")
    say("a multiplicative factor that grows as the level tightens.")
    say("")
    say(f"{'n':>6} {'level':>7} {'abs miss':>10} {'rate asked':>11} "
        f"{'rate got':>10} {'factor':>8}")
    say("-" * 104)
    worst = None
    for n in (50, 200, 1000):
        for level in (0.90, 0.95, 0.99, 0.999):
            r = exceedance_factor(n, level)
            if r is None:
                say(f"{n:>6} {level:>7.3f}   infeasible at this n")
                continue
            say(f"{n:>6} {level:>7.3f} {r['abs']:>10.5f} {r['rate_want']:>11.5f} "
                f"{r['rate_got']:>10.5f} {r['factor']:>8.2f}x")
            if worst is None or r["factor"] > worst[0]:
                worst = (r["factor"], n, level)
        say("")
    if worst:
        say(f"Worst factor here: {worst[0]:.2f}x at n={worst[1]}, level={worst[2]}.")
    say("The absolute column is flat and the factor column is not. A reader who")
    say("judges the defect by the absolute column is reading the one that does not")
    say("depend on the level they asked for.")

    path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                        OUT)
    with open(path, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"\nwritten -> {path}")


if __name__ == "__main__":
    main()
